/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './**/*.html',
    '!./node_modules/**',
  ],
  theme: {
    extend: {
      colors: {
        'brand-magenta': '#D9006C',
        'brand-black': '#000000',
        'brand-gray-light': '#94A3B8',
        'brand-gray-medium': '#64748B',
        'brand-gray-dark': '#334155',
        'brand-gray-darker': '#1E293B',
        'digital-purple': '#6366F1',
        'digital-cyan': '#06B6D4',
        'digital-blue': '#3B82F6',
        'print-orange': '#F97316',
        'print-green': '#22C55E',
        'web-green': '#10B981',
        'yacht-navy': '#1E3A5F',
        'yacht-gold': '#D4A853',
        'yacht-blue': '#2563EB',
        'textile-red': '#DC2626',
        'textile-gold': '#D97706',
        'textile-blue': '#2563EB',
        'textile-purple': '#7C3AED',
        'floc-cyan': '#06B6D4',
        'floc-orange': '#F97316',
        'floc-purple': '#8B5CF6',
        'floc-yellow': '#EAB308',
        'work-blue': '#1D4ED8',
        'work-green': '#059669',
        'work-orange': '#EA580C',
        'web-yellow': '#EAB308',
      },
      fontFamily: {
        heading: ['Poppins', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
